name: Actions Workflow

on: [push]

jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps:
            - name: list files
              run: |
                 pwd
                 ls
            - name: js action
              id: greet
              uses: actions/hello-world-javascript-action@v1 
              #input
              with: 
                who-to-greet: eman
            #output    
            - name: log greeting time
              run: echo "${{steps.greet.outputs.time}}"