name: Shell Commands
# when to perform this workflow
on: [push]
# each workflow can have one or more jobs
jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string 
        run: echo "Hello Github"
      - name: multiline script
        run: |  
          node -v
          npm -v
      - name: python commmand
        run: |
          import platform
          print(platform.processor()) 
#prints the processor on which workflow is running
        shell: python
  run-winndows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"] # to run them in series not in parallel
    steps:
      - name: directory powershell # default for windows
        run: get-location
      - name: directory bash
        run: pwd
        shell: bash
  
